import { Link } from "react-router-dom";

let timelineElements = [
  {
    id: 1,
    tag: "Learnings",
    title: "Started Learning Python",
    keyPoints: [
      { text: "Begin my programming journey with learning Python." },
      // { text: "Begin my programming journey with learning Python.", link: "https//:a1.com" },
      // { text: "KP1" },
      // { text: "KP2" },
    ],
    month: "June 2020",
    year: null,
  },
  {
    id: 2,
    tag: "Learnings",
    title: "Explored Animation&Graphics",
    keyPoints: [
      {text: "MyDesigns", link: "GitHub"},
      { text: " Animate • Photoshop • After Effects • Illustrator • InDesign), " },
      {text: "╾┅┅┅┅"},
      { text: "Dived into the realm of animation and graphics, mastering Adobe tools for video editing and more, broadening my skill set in multimedia.", link: "https://example.com/report" },
    ],
    month: "July 2020",
    year: null,
  },
  {
    id: 3,
    tag: "Experiences",
    title: "Volunteer at Mindler_Pvt_Ltd.",
    keyPoints: [
      { text: "Contributed to mission by providing valuable assistance to students in navigating scholarship opportunities, ensuring equitable access to education and fostering academic success." }
    ],
    month: "October",
    year: 2020,
  },
  // {
  //   id: 4,
  //   tag: "Experiences",
  //   title: "Work Experience1",
  //   keyPoints: [
  //     { text: "Brought 20% growth." },
  //     {
  //       parts: [
  //         { text: "Contributed to performance", link: "https://example.com/performance" },
  //         { text: " and increased performance.", link: "https://example.com/check" },
  //         { text: " Performance checked." },
  //         { text: "Contributed to performance", link: "https://example.com/performance" },
  //         { text: " and increased performance.", link: "https://example.com/check" },
  //         { text: " Performance checked." }
  //       ]
  //     },
  //     { text: "Brought Growth To WiFi" },
  //     { text: "Brought Growth To WiFi" },
  //     { text: "Brought Growth To WiFi" },
  //     { text: "Brought Growth To WiFi" },
  //     { text: "Brought Growth To WiFi" },
  //   ],
  //   month: "December",
  //   year: 2020
  // }
  ,
  {
    id: 4,
    tag: "Education",
    title: "Commenced B.Tech in Electronics_and_Communication_Engineering",
    keyPoints: [
      { text: "Embarked on an enriching academic journey pursuing a Bachelor of Technology degree in Electronics and Communication Engineering, laying the groundwork for a future career in the dynamic field of technology and innovation." },
    ],
      month: "November",
      year: 2020,
  },
  {
    id: 5,
    tag: "Projects",
    title: "Developed CLI_Cricket_Game",
    keyPoints: [
      {text: "Designed and implemented an engaging Command Line Interface (CLI) cricket game named 'crickPy' using Python. Check out, here.", link: "https://github.com/lakshay-nasa/CricketPy"},
    ],
    month: "December",
    year: 2020,
  },
  {
    id: 6,
    tag: "Learnings",
    title: "Git/GitHub & Open-Source",
    keyPoints: [
      {text: "Lakshay Nasa -> GitHub", link: "https://github.com/lakshay-nasa"},
      { text: "Initiated exploration into the world of version control with Git, GitHub, and open-source principles, gaining valuable insights into collaborative software development practices and fostering a deeper understanding of code management and sharing within the global community. "}
    ],
    month: "February",
    year: 2021,
  },
  {
    id: 7,
    tag: "Learnings",
    title: "Cloud Computing with Google_Cloud_Platform",
    keyPoints: [
      {text: "QwikLab-Profile", link: "https://www.cloudskillsboost.google/public_profiles/4dd9cc5c-0f66-4ad6-85be-1e8f066bd6b0"},
      { text: "Acquired expertise in cloud computing through hands-on learning with Google Cloud Platform (GCP), mastering essential infrastructure and deployment techniques. Ready to leverage cloud technologies for innovative projects." },
    ],
    month: "April 2021",
    year: null,
  },
  {
    id: 8,
    tag: "Learnings",
    title: "Diving into DevOps: Docker and Kubernetes",
    keyPoints: [
      { text: "Began my exploration into DevOps, gaining foundational knowledge in Kubernetes and Docker to streamline and scale deployment processes." },
    ],
    month: "May  2021",
    year: null,
  },
  {
    id: 9,
    tag: "Achievements",
    title: "JFrog Challenge Completion: Gateway_to_DevOps",
    keyPoints: [
      { text: "Conquered the JFrog Challenge, gaining an basic understanding of DevOps principles essential for efficient software development and deployment."},
      {text: "Check out my contribution, here.", link: "https://github.com/lakshay-nasa/jfrog-docker-repo-simple-example"}
    ],
    month: "May 2021",
    year: null,
  },
  {
    id: 10,
    tag: "Achievements",
    title: "Contributed to Open-Source-Day",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/renana/osd-github-101"},
      // { text: "Contributed to OSD." },
    ],
    month: "July 2021",
    year: null,
  },
  {
    id: 11,
    tag: "Learnings",
    title: "Journey through Database: MySQL_CloudDatabases, PostgreSQL_MogoDB",
    keyPoints: [
      {text: "Embarked on a comprehensive exploration of database technologies, delving into MySQL, PostgreSQL, and MongoDB to deepen my understanding of data storage and management solutions, facilitating efficient handling of diverse data types."},
      // { text: "Contributed to OSD." },
    ],
    month: "July 2021",
    year: null,
  },
  {
    id: 12,
    tag: "Projects",
    title: "Remote-Control-System for Farms.",
    keyPoints: [
      {text: "Know_More", link: "https://lakshay-nasa.github.io/docs/automation.html"},
      { text: "Arduino | Relay | Sensors | Bluetooth Module." },
      { text: "A real-time project that enables farmers to control and power their farming tools remotely and not suffer unpleasant weather." },
    ],
    month: "September",
    year: 2021,
  },
  {
    id: 13,
    tag: "Learnings",
    title: "Architecting with Google_Compute_Engine",
    keyPoints: [
      {text: "Certificate", link: "https://www.coursera.org/account/accomplishments/specialization/CUCCQGX4K7VS"},
      { text: "Enhanced my expertise in cloud architecture and Google Cloud Platform (GCP) services."},
    ],
    month: "October",
    year: 2021,
  },
  {
    id: 14,
    tag: "Achievements",
    title: "Winner of the Machine Learning Track in Google-Devfest.",
    keyPoints: [
      { text: "Achieved victory in Google Cloud DevFest's machine learning track, demonstrating expertise in ML concepts and practical GCP application."},
    ],
    month: "November",
    year: 2021,
  },
  {
    id: 15,
    tag: "Learnings",
    title: "AWS Educate Program",
    keyPoints: [
      { text: "Elevated my cloud computing skills through hands-on experience with Amazon Web Services with AWS Educate."},
    ],
    month: "December",
    year: 2021,
  },
  {
    id: 16,
    tag: "Learnings",
    title: "WebDev Learnings",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/Website-Templates"},
      { text: "Practiced web-templates with Flask API."},
    ],
    month: "December",
    year: 2021,
  },
  {
    id: 17,
    tag: "Experiences",
    title: "Campus Leader - TechLearn",
    keyPoints: [
      { text: "Mentored Students to learn the latest technologies. Spreaded awareness about Tech Learn Sessions."},
    ],
    month: "December",
    year: 2021,
  },
  {
    id: 18,
    tag: "Learnings",
    title: "Hosting Open-Source Session.",
    keyPoints: [
      { text: "Took on the role of host for an open source session within the student community."},
    ],
    month: "January",
    year: 2022,
  },
  {
    id: 19,
    tag: "Learnings",
    title: "Contributed To Data-On-K8s-Community",
    keyPoints: [
      {text: "Dok-Community", link: "https://dok.community/"},
      { text: "Contributed to the Data On Kubernetes Community, gaining skills in problem-solving, Docker products, and project management while advancing stateful applications on Kubernetes."},
    ],
    month: "January",
    year: 2022,
  },
  {
    id: 20,
    tag: "Experiences",
    title: "DevRel & CM Intern - Data_On_Kubernetes_Community",
    keyPoints: [
      { text: "Advocacy ╿ Back-end Operations • Databases • Analytical Skills • Kubernetes " },
      {text: "╾┉┉"},
      {text: "⚫ Led the design team, creating content, animations, and graphics for community growth. - Link", link: "https://github.com/lakshay-nasa/DoK-Vocabulary-Cards"},
      { text: "⚪ Collaborated with the Transcript Team to finalised 10+ scripts with flawless accuracy."},
      { text: "⚫ Authored and published growth topics/blogs to drive engagements."},
      { text: "⚪ Contributed to development of technologies and open-source projects focused on running data on Kubernetes."},
    ],
    month: "January",
    year: 2022,
  },
  {
    id: 21,
    tag: "Projects",
    title: "Full-Stack-Developer-Pathway",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/Full-Stack-Developer-Pathway"},
      { text: "A comprehensive project encapsulating my journey through the Full Stack Developer Pathway, encompassing both backend and frontend learning tracks."},
    ],
    month: "Feburary",
    year: 2022,
  },
  {
    id: 22,
    tag: "Projects",
    title: "Contributed To dokc.github.io",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/dokc.github.io"},
      { text: "Collaborated on building the dokc.github.io website using Docusaurus, establishing a comprehensive platform dedicated to all aspects of Data On Kubernetes."},
    ],
    month: "Feburary",
    year: 2022,
  },
  {
    id: 23,
    tag: "Projects",
    title: "Graphics - DoKCards",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/DoK-Vocabulary-Cards"},
      { text: "Crafted and designed DoK Learning Cards, streamlining the process of mastering Kubernetes vocabulary for enhanced learning efficiency."},
    ],
    month: "March",
    year: 2022,
  },
  {
    id: 24,
    tag: "Projects",
    title: "Learn CPP_Programming",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/Learn-CPP"},
      { text: "Mastering the C++ programming language through structured learning and practical exercises."},
    ],
    month: "March",
    year: 2022,
  },
  {
    id: 25,
    tag: "Projects",
    title: "Run Databases on K8's - how_to_DoK",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/dokc/explorers"},
      // {text: " Argo Workflows • K8ssandra • "},
      { text: "⚫ Contributed to the 'How To (Get) Data on Kubernetes' project, aimed at developing knowledge, practice, and examples for running various data use cases on Kubernetes. "},
      { text: "⚪ Involved in designing cloud-native data workflows, utilizing Argo Workflows and K8ssandra, and actively participated in project management, content creation, and community engagement efforts. "},
    ],
    month: "April 2022",
    year: null,
  },
  {
    id: 26,
    tag: "Learnings",
    title: "Delivered a talk at DoK-Students-Day.",
    keyPoints: [
      {text: "YouTube", link: "https://www.youtube.com/watch?v=O0Vo3Wes9Zk"},
      { text: "Delivered a talk at DoK Students Day about Things to learn berfore doing Data On Kubernetes."},
    ],
    month: "May 2022",
    year: null,
  },
  {
    id: 27,
    tag: "Projects",
    title: "WeatherApp",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/WeatherApp"},
      { text: "A personal project built for understanding APIs. The application provides real-time weather details with images of the searched place in the background."},
    ],
    month: "June",
    year: 2022,
  },
  {
    id: 28,
    tag: "Learnings",
    title: "Exploring Deployment with Heroku",
    keyPoints: [
      {text: "Heroku", link: "https://www.heroku.com/"},
      {text: "╾┉┉"},
      {text: "Learned how to deploy applications effectively using Heroku, enhancing my understanding of cloud-based hosting and deployment workflows."},
    ],
    month: "June",
    year: 2022,
  },
  {
    id: 29,
    tag: "Achievements",
    title: "Postman student expert - API",
    keyPoints: [
      {text: "Postman", link: "https://www.postman.com/"},
      { text: "Attained the title of Postman Student Expert, demonstrating proficiency in API testing and collaboration through the Postman platform."},
    ],
    month: "July",
    year: 2022,
  },
  {
    id: 30,
    tag: "Education",
    title: "Honours in Machine Learning Education",
    keyPoints: [
      { text: "Pursued an Honours in Machine Learning, delving deep into advanced concepts and methodologies to broaden expertise in this rapidly evolving field."},
    ],
    month: "July",
    year: 2022,
  },
  {
    id: 31,
    tag: "Learnings",
    title: "DSA-Kit",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/DSA-Kit"},
      { text: "Project to systematically enhance my data structures and algorithms expertise, facilitating efficient problem-solving and coding proficiency."},
    ],
    month: "August",
    year: 2022,
  },
  {
    id: 32,
    tag: "Learnings",
    title: "Pixel View",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/pixel-view"},
      { text: "Created a pixel art representation of Mario using CSS, exploring the nuances of design and style in web development."},
    ],
    month: "August",
    year: 2022,
  },
  {
    id: 33,
    tag: "Experiences",
    title: "Software Engineer Internship - Rennovation_Software",
    keyPoints: [
      {text: " Python • Back-end Operations • NodeJS • Flask/Fast • Django • API"},
      {text: "╾┉┉"},
      { text: "⚪ Worked with the team to ensure alignment and process efficiency of release."},
      { text: "⚫ Build the back-end, integrated Rest APIs."},
      { text: "⚪ Develop application features and improvements."},
    ],
    month: "August",
    year: 2022,
  },
  {
    id: 34,
    tag: "Experiences",
    title: "Open Source Lead - GDSC",
    keyPoints: [
      {text: "GDSC_DCRUST", link: "https://gdsc.community.dev/"},
      { text: "Open Source Development • Project Plans • Teamwork • Organization Skills • Project Management"},
      {text: "╾┉┉"},
      {text: "⚪ Spearheaded open-source endeavors at GDSC, orchestrating projects, nurturing collaboration, and cultivating an environment of innovation and knowledge-sharing within the developer community."},
    ],
    month: "September",
    year: 2022,
  },
  {
    id: 35,
    tag: "Learnings",
    title: "Contribution to gRPC",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/grpc/grpc"},
      { text: "Contributed to the gRPC framework,"},
    ],
    month: "September",
    year: 2022,
  },
  {
    id: 36,
    tag: "Learnings",
    title: "Immersed in UI/UX with Figma",
    keyPoints: [
      {text: "Figma", link: "https://www.figma.com/"},
      { text: "Immersed myself in the world of UI/UX design, harnessing the power of Figma to craft captivating and user-friendly interfaces that elevate the digital experience."},
    ],
    month: "September",
    year: 2022,
  },
  {
    id: 37,
    tag: "Learnings",
    title: "Diving Into Golang",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/Learn-Golang"},
      { text: "Embarked on a journey to learn Golang, focusing on its robust features for building efficient, scalable applications."},
    ],
    month: "September",
    year: 2022,
  },
  {
    id: 38,
    tag: "Learnings",
    title: "Hosted Session: Intro_to_Git&GitHub",
    keyPoints: [
      {text: "GDSC DCRUST", link: "https://gdsc.community.dev/events/details/developer-student-clubs-deenbandhu-chhotu-ram-university-of-science-technology-murthal-presents-intro-to-git-and-github/"},
      { text: "Led a session introducing Git and GitHub, empowering participants with fundamental version control and collaborative software development skills."},
    ],
    month: "October",
    year: 2022,
  },
  {
    id: 39,
    tag: "Learnings",
    title: "Android-Development",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/Android-Development"},
      { text: " Kotlin • Android Studio • Firebase • Jetpack Compose "},
      { text: "Delved into the world of Android development, acquiring skills to create innovative and user-friendly mobile applications for the Android platform."},
    ],
    month: "October",
    year: 2022,
  },
  {
    id: 40,
    tag: "Projects",
    title: "CircleEver",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/CircleEver"},
      { text: " Kotlin • Android Application • Firebase • Jetpack Compose "},
      { text: "An award-winning android application to connect University students with diverse societies."},
    ],
    month: "November",
    year: 2022,
  },
  {
    id: 41,
    tag: "Learnings",
    title: "Immersion in Machine Learning",
    keyPoints: [
      { text: "GitHub", link: "https://github.com/lakshay-nasa/Machine-Learning"},
      { text: " Image Processing • NLP • anomaly detection • Computer Vision • Data Analysis"},
      { text: " Submerged myself in the vast realm of machine learning, mastering techniques to create intelligent systems that can extract insights and make predictions from data. "},
    ],
    month: "November",
    year: 2022,
  },
  {
    id: 42,
    tag: "Learnings",
    title: "Image Processing and Signal Analysis: MATLAB",
    keyPoints: [
      { text: " Acquired proficiency in MATLAB, specializing in image processing and signals analysis, unlocking the ability to manipulate and analyze visual and audio data with precision and efficiency. "},
    ],
    month: "December",
    year: 2022,
  },
  {
    id: 43,
    tag: "Learnings",
    title: "Contributed to Ovio.hub",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/oviohub"},
      { text: " Contributed to the development of Ovio.hub, a platform aimed at revolutionizing collaborative workspace management. "},
    ],
    month: "February",
    year: 2023,
  },
  {
    id: 44,
    tag: "Projects",
    title: "Tech-Sandbox",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/Tech-Sandbox"},
      { text: "A dedicated space for experimenting, testing, and debugging a variety of programs, applications, and projects. It aims to deepen my understanding of software and uncover new functionalities or capabilities through hands-on exploration and experimentation."},
    ],
    month: "February",
    year: 2023,
  },
  {
    id: 45,
    tag: "Learnings",
    title: "Hosted a Hackathon_event",
    keyPoints: [
      // {text: "YouTube", link: "https://www.youtube.com/watch?v=O0Vo3Wes9Zk"},
      { text: "Organized and led a programming hackathon, providing participants with an opportunity to showcase their coding skills and creativity."},
    ],
    month: "March 2023",
    year: null,
  },
  {
    id: 46,
    tag: "Learnings",
    title: "Worked with Apertium",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/lakshay-nasa/Tech-Sandbox"},
      { text: "a free and open-source platform for rule-based machine translation. "},
    ],
    month: "May 2022",
    year: null,
  },
  {
    id: 47,
    tag: "Projects",
    title: "Contributed to Move2Kube",
    keyPoints: [
      {text: "GitHub", link: "https://github.com/konveyor"},
      // {text: "╾┅┅┅┅"},
      { text: "Actively contributed to the Move2Kube project, an initiative focused on automating the migration of traditional applications to Kubernetes. Collaborated with a diverse team to enhance migration strategies, improve tooling, and streamline the Kubernetes adoption process for organizations."},
    ],
    month: "May 2022",
    year: null,
  },
  {
    id: 48,
    tag: "Experiences",
    title: "Community Operations • KodeKloud",
    keyPoints: [
      { text: "Advocacy ╿ Back-end Operations • Databases • Analytical Skills • Kubernetes " },
      {text: "╾┅┅┅┅"},
      {text: "⚫ Led the design team, creating content, animations, and graphics for community growth. - Link", link: "https://github.com/lakshay-nasa/DoK-Vocabulary-Cards"},
      { text: "⚪ Collaborated with the Transcript Team to finalised 10+ scripts with flawless accuracy."},
      { text: "⚫ Authored and published growth topics/blogs to drive engagements."},
      { text: "⚪ Contributed to development of technologies and open-source projects focused on running data on Kubernetes."},
    ],
    month: "June",
    year: 2023,
  },
  {
    id: 49,
    tag: "Experiences",
    title: "AI Intern ╼ Defence_Research_and_Development_Organisation",
    keyPoints: [
      { text: "Statistical Data Analysis • Image Processing • Artificial Intelligence (AI) " },
      {text: "╾┅┅┅┅"},
      { text: "Delivered a talk at DoK Students Day about Things to learn berfore doing Data On Kubernetes."},
    ],
    month: "July 2023",
    year: null,
  },
  {
    id: 50,
    tag: "Projects",
    title: "Slack Automation",
    keyPoints: [
      {text: "YouTube", link: "https://www.youtube.com/watch?v=O0Vo3Wes9Zk"},
      { text: "Delivered a talk at DoK Students Day about Things to learn berfore doing Data On Kubernetes."},
    ],
    month: "August 2023",
    year: null,
  },
  {
    id: 51,
    tag: "Projects",
    title: "Builded 3DvisioGen",
    keyPoints: [
      {text: "Demo", link: "https://lakshay-nasa.github.io/docs/visiogen.html"},
      { text: "Delivered a talk at DoK Students Day about Things to learn berfore doing Data On Kubernetes."},
    ],
    month: "September",
    year: 2023,
  },
  {
    id: 52,
    tag: "Projects",
    title: "Access Control System",
    keyPoints: [
      {text: "GitHub", link: "https://www.youtube.com/watch?v=O0Vo3Wes9Zk"},
      { text: "Statistical Data Analysis • Image Processing • Artificial Intelligence (AI) " },
      {text: "╾┅┅┅┅"},
      { text: "Developed an innovative access control system incorporating face recognition program. Designed and implemented a solution to authenticate and grant access to authorized personnel based on facial recognition, enhancing security and efficiency in access management."},
    ],
    month: "November",
    year: 2023,
  },
  {
    id: 53,
    tag: "Projects",
    title: "Pizzania - WebDev with Webflow",
    keyPoints: [
      {text: "Demo", link: "https://pizzania.webflow.io/"},
      { text: "Designed and developed the Pizzania website using Webflow, to create a stunning and responsive online presence for the pizza restaurant. "},
    ],
    month: "January",
    year: 2024,
  },
  {
    id: 54,
    tag: "Learnings",
    title: "Exploring Ruby On Rails",
    keyPoints: [
      {text: "GitHub", link: "https://www.youtube.com/watch?v=O0Vo3Wes9Zk"},
      { text: "Documenting my journey of mastering Ruby on Rails. This detailed learning pathway covers Ruby syntax, OPPs using RoR Concepts, Rails MVC architecture, and full-stack web development practices."},
    ],
    month: "February",
    year: 2024,
  },
  {
    id: 55,
    tag: "Projects",
    title: "API Development with Ruby on Rails",
    keyPoints: [
      {text: "GitHub", link: "https://www.youtube.com/watch?v=O0Vo3Wes9Zk"},
      { text: "RoR • API • PostgreSQL • Potman" },
      {text: "╾┅┅┅┅"},
      { text: "Developed a robust API using Ruby on Rails, integrating PostgreSQL for database management. Utilized Postman to rigorously test API functionalities, ensuring efficient data handling and reliable system performance."},
    ],
    month: "March 2024",
    year: null,
  },
  {
    id: 56,
    tag: "Learnings",
    title: "Apache Kafka",
    keyPoints: [
      {text: "GitHub", link: "https://www.youtube.com/watch?v=O0Vo3Wes9Zk"},
      { text: "Delivered a talk at DoK Students Day about Things to learn berfore doing Data On Kubernetes."},
    ],
    month: "April 2024",
    year: null,
  },
  {
    id: 57,
    tag: "Projects",
    title: "Apache Kafka Project",
    keyPoints: [
      {text: "GitHUb", link: "https://www.youtube.com/watch?v=O0Vo3Wes9Zk"},
      { text: "Delivered a talk at DoK Students Day about Things to learn berfore doing Data On Kubernetes."},
    ],
    month: "April 2024",
    year: null,
  },
];

export default timelineElements;
